<?php
/* Copyright (C) 2026 Pierre Ardoin <developpeur@lesmetiersdubatiment.fr> */

// Included by run_quartix.php: exercise the real association and deletion methods.
$associationService = new QxTestService($db);
foreach (array(3, 4) as $vehicleId) $db->query("INSERT INTO ".MAIN_DB_PREFIX."lmdbvehiclemanagement_vehicle (rowid,entity,ref,label,fk_user_creat,date_creation) VALUES (".$vehicleId.",1,'QX-".$vehicleId."','Test tracker transfer',1,'2026-01-01')");
$catalog = array(array('VehicleID' => 30, 'ShiftStartTime' => '08:00:00'));
$installed = strtotime('2026-08-29T06:00:00Z');
qxCheck(LmdbVehicleQuartixRules::firstUsageDay($installed, 'Europe/Paris', '08:00') === '2026-08-29', 'An exact shift start permits that full day');
qxCheck(LmdbVehicleQuartixRules::firstUsageDay($installed + 1, 'Europe/Paris', '08:00') === '2026-08-30', 'A partial installation day is excluded');
qxReject(static function () use ($associationService, $user, $catalog) { $associationService->associate($user, 3, 30, 'Europe/Paris', $catalog, dol_now() + 86400); }, 'QxInvalidAssociationDate');
qxReject(static function () use ($associationService, $user, $installed) { $associationService->associate($user, 3, 30, 'Europe/Paris', array(), $installed); }, 'QxInvalidResponse');
$associationService->associate($user, 3, 30, 'Europe/Paris', $catalog, $installed);
$transferLink = $associationService->link(3);
qxCheck($db->jdate($transferLink->sync_from) === $installed, 'Confirmed installation is persisted on the association');
qxReject(static function () use ($associationService, $user, $catalog, $installed) { $associationService->associate($user, 4, 30, 'Europe/Paris', $catalog, $installed); }, 'QxMappingExists');
$transferPosition = array_replace($position, array('VehicleID' => 30, 'LastEventDatetime' => '2026-08-30T12:00:00Z'));
$associationService->savePosition($transferLink, $transferPosition, 'offset');
$transferSummary = array_replace($summary, array('VehicleID' => 30));
$associationService->saveUsage($transferLink, array($transferSummary), '2026-08-30', '2026-08-30');
$transferReading = new QxTestReading($db);
$transferEstimateId = $transferReading->saveQuartix($user, 3, 30, $estimateDate, '2026-08-30', 800.0);
qxCheck($transferEstimateId > 0, 'Source vehicle receives a QUARTIX estimate');
qxReject(static function () use ($associationService, $user, $transferLink) { $associationService->disassociate($user, 3, (int) $transferLink->rowid, 'invalid'); }, 'QxInvalidSettings');
$user->admin = 0;
qxReject(static function () use ($associationService, $user, $transferLink) { $associationService->disassociate($user, 3, (int) $transferLink->rowid, 'error'); }, 'QxAccessDenied');
qxCheck($transferReading->deleteQuartix($user) < 0, 'Import purge requires configuration rights');
$user->admin = 1;
$conf->entity = 2;
$mc = new class { public function getEntity($element, $shared = 1, $object = null) { return '1,2'; } };
qxReject(static function () use ($associationService, $user, $transferLink) { $associationService->disassociate($user, 3, (int) $transferLink->rowid, 'error'); }, 'QxAccessDenied');
qxCheck($transferReading->deleteQuartix($user) < 0, 'Shared vehicle cannot be purged from the consulting entity');
$conf->entity = 1; $mc = null;
QxTestVehicle::$failTrigger = true;
qxReject(static function () use ($associationService, $user, $transferLink) { $associationService->disassociate($user, 3, (int) $transferLink->rowid, 'reassignment'); }, 'QxDatabaseError');
QxTestVehicle::$failTrigger = false;
qxCheck($associationService->link(3) !== null && $associationService->position(3) !== null, 'Unlink trigger failure restores both link and GPS');
$associationService->setActive($user, 3, 0);
$associationService->disassociate($user, 3, (int) $transferLink->rowid, 'reassignment');
qxCheck($associationService->link(3) === null && $associationService->position(3) === null, 'A paused association can be unlinked and its GPS is cleared');
qxCheck($transferReading->fetch($transferEstimateId) > 0 && $associationService->usage(3, '2026-08-01', '2026-08-31', 'day')[0]->distance == 42.5, 'Reassignment retains imported mileage and usage on the source vehicle');
$eventsBeforeReplay = QxTestVehicle::$events;
$associationService->disassociate($user, 3, (int) $transferLink->rowid, 'error');
qxCheck(QxTestVehicle::$events === $eventsBeforeReplay && $transferReading->fetch($transferEstimateId) > 0, 'Replayed confirmation cannot purge history after unlink');
qxReject(static function () use ($associationService, $user, $catalog, $installed) { $associationService->associate($user, 3, 30, 'Europe/Paris', $catalog, $installed); }, 'QxAssociationHistoryOverlap');
$reinstalled = strtotime('2026-08-31T12:00:00Z');
$associationService->associate($user, 4, 30, 'Europe/Paris', $catalog, $reinstalled);
$targetLink = $associationService->link(4);
qxCheck($targetLink->usage_cursor === null && $targetLink->odometer_synced === null, 'Reassigned tracker starts with independent sync cursors');
qxReject(static function () use ($associationService, $targetLink, $transferPosition) { $associationService->savePosition($targetLink, $transferPosition, 'offset'); }, 'QxBeforeAssociation');
qxCheck($transferReading->saveQuartix($user, 4, 30, $estimateDate, '2026-08-30', 800.0) < 0 && $transferReading->error === 'QxBeforeAssociation', 'Previous vehicle mileage cannot be imported on the new vehicle');
qxReject(static function () use ($associationService, $targetLink, $transferSummary) { $associationService->saveUsage($targetLink, array($transferSummary), '2026-08-30', '2026-08-30'); }, 'QxBeforeAssociation');
$transferPosition['LastEventDatetime'] = '2026-09-01T12:00:00Z';
$associationService->savePosition($targetLink, $transferPosition, 'offset');
$transferSummary['Date'] = '2026-09-01';
$associationService->saveUsage($targetLink, array($transferSummary), '2026-09-01', '2026-09-01');
$targetEstimateId = $transferReading->saveQuartix($user, 4, 30, strtotime('2026-09-01T12:00:00Z'), '2026-09-01', 900.0);
qxCheck($targetEstimateId > 0 && $associationService->position(4) !== null, 'Post-installation imports remain available');
$manual = new QxTestReading($db); $manual->fk_vehicle = 4; $manual->reading_date = strtotime('2026-09-01T13:00:00Z'); $manual->odometer_km = 950;
qxCheck($manual->create($user) > 0, 'Manual reading coexists with imports');
$charge = new QxTestReading($db); $charge->fk_vehicle = 4; $charge->reading_date = strtotime('2026-09-01T14:00:00Z'); $charge->odometer_km = 980;
$db->begin(); qxCheck($charge->createFromConsumption($user) > 0, 'Consumption reading coexists with imports'); $db->commit();
qxCheck($manual->deleteQuartix($user) < 0 && $charge->deleteQuartix($user) < 0, 'Dedicated purge refuses real readings and consumption-owned readings');
$db->failPattern = 'DELETE FROM '.MAIN_DB_PREFIX.'lmdbvehiclemanagement_qx_usage';
qxReject(static function () use ($associationService, $user, $targetLink) { $associationService->disassociate($user, 4, (int) $targetLink->rowid, 'error'); }, 'QxDatabaseError');
$db->failPattern = '';
qxCheck($transferReading->fetch($targetEstimateId) > 0 && $associationService->link(4) !== null && $associationService->position(4) !== null, 'Purge failure restores deleted estimates, usage, position and association');
$associationService->disassociate($user, 4, (int) $targetLink->rowid, 'error');
qxCheck($transferReading->fetch($targetEstimateId) === 0 && $associationService->usage(4, '2026-08-01', '2026-09-05', 'day') === array(), 'Erroneous association purges QUARTIX mileage and summaries');
qxCheck($associationService->link(4) === null && $associationService->position(4) === null, 'Purge frees tracker and removes GPS');
qxCheck($manual->fetch((int) $manual->id) > 0 && $charge->fetch((int) $charge->id) > 0 && $transferReading->fetch($transferEstimateId) > 0, 'Purge preserves manual/consumption readings and history on other vehicles');
qxCheck($service->position(1) !== null && $service->link(1) !== null, 'Unrelated association remains untouched');
$associationService->associate($user, 4, 30, 'Europe/Paris', $catalog, $reinstalled);
qxReject(static function () use ($associationService, $user, $targetLink) { $associationService->disassociate($user, 4, (int) $targetLink->rowid, 'error'); }, 'QxAssociationChanged');
qxCheck($associationService->link(4) !== null, 'Stale confirmation cannot remove a replacement association');
$db->query('UPDATE '.MAIN_DB_PREFIX.'lmdbvehiclemanagement_qx_job SET retry_at=NULL,last_vehicle=0 WHERE entity=1');
$boundaryCron = new QxTestCron($db); $boundaryCron->client = new QxTestClient($db, 1);
$boundaryCron->client->responses = array_fill(0, 21, qxResponse(array()));
qxCheck($boundaryCron->usage() === 0, 'Reassigned tracker runs through the actual worker');
$targetCall = $boundaryCron->client->calls[count($boundaryCron->client->calls) - 1];
qxCheck($targetCall['values']['VehicleIDList'] === '30' && $targetCall['values']['StartDay'] >= '2026-09-01', 'Worker bounds the first refresh at the installation day');
qxCheck($associationService->usage(3, '2026-08-01', '2026-08-31', 'day')[0]->distance == 42.5, 'Retention keeps the previous vehicle history after reassignment');
