<?php
/* Copyright (C) 2026 Pierre Ardoin <developpeur@lesmetiersdubatiment.fr> */
$res = 0;
if (!$res && !empty($_SERVER['CONTEXT_DOCUMENT_ROOT'])) $res = @include str_replace('..', '', $_SERVER['CONTEXT_DOCUMENT_ROOT']).'/main.inc.php';
if (!$res && file_exists('../../main.inc.php')) $res = @include '../../main.inc.php';
if (!$res && file_exists('../main.inc.php')) $res = @include '../main.inc.php';
if (!$res) die('Include of main fails');
require_once DOL_DOCUMENT_ROOT.'/comm/action/class/actioncomm.class.php'; dol_include_once('/lmdbvehiclemanagement/class/lmdbvehicleregulatorycontrol.class.php'); dol_include_once('/lmdbvehiclemanagement/lib/lmdbvehiclemanagement.lib.php');
/** @var Conf $conf */ /** @var DoliDB $db */ /** @var Translate $langs */ /** @var User $user */
$langs->loadLangs(array('agenda', 'users', 'lmdbvehiclemanagement@lmdbvehiclemanagement')); $id = GETPOSTINT('id'); $limit = GETPOSTINT('limit') ?: (int) $conf->liste_limit; $page = GETPOSTISSET('pageplusone') ? GETPOSTINT('pageplusone') - 1 : GETPOSTINT('page'); if ($page < 0 || GETPOST('button_search', 'alpha') || GETPOST('button_removefilter', 'alpha')) $page = 0; $offset = $limit * $page; $sortfield = GETPOST('sortfield', 'aZ09comma') ?: 'a.datep'; $sortorder = strtoupper(GETPOST('sortorder', 'alpha')) === 'ASC' ? 'ASC' : 'DESC'; if (!in_array($sortfield, array('a.ref', 'a.datep', 'a.label', 'a.code', 'a.percent', 'u.lastname'), true)) $sortfield = 'a.datep'; $searchLabel = GETPOST('search_label', 'alphanohtml'); if (GETPOST('button_removefilter', 'alpha')) $searchLabel = '';
$object = new LmdbVehicleRegulatoryControl($db); if (!isModEnabled('lmdbvehiclemanagement') || !isModEnabled('agenda') || !lmdbVehicleManagementCanDo($user, 'read') || !empty($user->socid)) accessforbidden(); if ($id <= 0 || $object->fetch($id) <= 0) accessforbidden($langs->trans('RecordNotFound')); $canReadAllAgenda = $user->hasRight('agenda', 'allactions', 'read'); if (!$user->hasRight('agenda', 'myactions', 'read') && !$canReadAllAgenda) accessforbidden();
$where = lmdbVehicleRegulatoryControlAgendaWhere($object, 'a'); if ($searchLabel !== '') $where .= natural_search('a.label', $searchLabel); $resCount = $db->query('SELECT COUNT(*) AS total FROM '.MAIN_DB_PREFIX.'actioncomm AS a'.$where); if (!$resCount) { dol_print_error($db); exit; } $countRow = $db->fetch_object($resCount); $total = is_object($countRow) ? (int) $countRow->total : 0; $db->free($resCount); if ($offset > $total) { $page = 0; $offset = 0; } $sql = 'SELECT a.id, a.ref, a.datep, a.code, a.label, a.percent, a.fk_user_author, a.fk_user_action, u.login, u.firstname, u.lastname FROM '.MAIN_DB_PREFIX.'actioncomm AS a LEFT JOIN '.MAIN_DB_PREFIX.'user AS u ON u.rowid = a.fk_user_action'.$where.$db->order($sortfield, $sortorder).$db->plimit($limit + 1, $offset); $resql = $db->query($sql); if (!$resql) { dol_print_error($db); exit; } $num = $db->num_rows($resql); $form = new Form($db);
llxHeader('', $object->ref.' - '.$langs->trans('EventsAgenda'), '', '', 0, 0, '', '', '', 'mod-lmdbvehiclemanagement page-card_agenda'); $head = lmdbVehicleRegulatoryControlPrepareHead($object); print dol_get_fiche_head($head, 'agenda', $langs->trans('RegulatoryControl'), -1, $object->picto); lmdbVehicleRegulatoryControlPrintBanner($object); $param = '&id='.$id.'&search_label='.urlencode($searchLabel); $origin = urlencode($object->element.'@'.$object->module); $backtopage = urlencode($_SERVER['PHP_SELF'].'?id='.$id); $newButton = dolGetButtonTitle($langs->trans('AddAction'), '', 'fa fa-plus-circle', DOL_URL_ROOT.'/comm/action/card.php?action=create&token='.newToken().'&origin='.$origin.'&originid='.$id.'&backtopage='.$backtopage, '', $user->hasRight('agenda', 'myactions', 'create') || $user->hasRight('agenda', 'allactions', 'create'));
print '<form method="POST" action="'.$_SERVER['PHP_SELF'].'"><input type="hidden" name="token" value="'.newToken().'"><input type="hidden" name="id" value="'.$id.'"><input type="hidden" name="sortfield" value="'.dol_escape_htmltag($sortfield).'"><input type="hidden" name="sortorder" value="'.dol_escape_htmltag($sortorder).'">'; print_barre_liste($langs->trans('EventsAgenda'), $page, $_SERVER['PHP_SELF'], $param, $sortfield, $sortorder, '', $num, $total, 'calendar', 0, $newButton, '', $limit, 0, 0, 1); print '<div class="div-table-responsive-no-min"><table class="noborder centpercent liste"><tr class="liste_titre_filter"><td></td><td></td><td></td><td></td><td><input class="flat maxwidth300" name="search_label" value="'.dol_escape_htmltag($searchLabel).'"></td><td>'.$form->showFilterButtons().'</td></tr><tr class="liste_titre">'; foreach (array('Ref' => 'a.ref', 'Date' => 'a.datep', 'Owner' => 'u.lastname', 'Type' => 'a.code', 'Title' => 'a.label', 'Status' => 'a.percent') as $label => $field) print getTitleFieldOfList($label, 0, $_SERVER['PHP_SELF'], $field, '', $param, $field === 'a.percent' ? 'class="center"' : '', $sortfield, $sortorder); print '</tr>';
$rendered = 0; while ($rendered < min($num, $limit) && is_object($row = $db->fetch_object($resql))) { $agendaObject = new ActionComm($db); $agendaObject->id = (int) $row->id; $agendaObject->ref = (string) $row->ref; $agendaObject->label = (string) $row->label; $agendaObject->datep = $db->jdate($row->datep); $agendaObject->percentage = (int) $row->percent; $agendaObject->authorid = (int) $row->fk_user_author; $agendaObject->userownerid = (int) $row->fk_user_action; $agendaObject->type_code = (string) $row->code; if (!$canReadAllAgenda) $agendaObject->userassigned[(int) $user->id] = array('id' => (int) $user->id, 'transparency' => 0); $owner = new User($db); $owner->id = (int) $row->fk_user_action; $owner->login = (string) $row->login; $owner->firstname = (string) $row->firstname; $owner->lastname = (string) $row->lastname; $owner->statut = 1; print '<tr class="oddeven"><td>'.$agendaObject->getNomUrl(1).'</td><td>'.dol_print_date($agendaObject->datep, 'dayhour').'</td><td>'.($owner->id > 0 ? $owner->getNomUrl(1) : '').'</td><td>'.dol_escape_htmltag((string) $row->code).'</td><td>'.dol_escape_htmltag((string) $row->label).'</td><td class="center">'.$agendaObject->LibStatut((int) $row->percent, 5).'</td></tr>'; $rendered++; }
if ($rendered === 0) print '<tr class="oddeven"><td colspan="6"><span class="opacitymedium">'.$langs->trans('NoRecordFound').'</span></td></tr>'; print '</table></div></form>'; $db->free($resql); print dol_get_fiche_end(); llxFooter(); $db->close();
