CREATE TABLE llx_lmdbvehiclemanagement_vehicle (
	rowid integer AUTO_INCREMENT PRIMARY KEY,
	entity integer DEFAULT 1 NOT NULL,
	ref varchar(128) NOT NULL,
	registration_number varchar(32) NOT NULL,
	vin varchar(64) DEFAULT NULL,
	label varchar(255) NOT NULL,
	brand varchar(128) DEFAULT NULL,
	model varchar(128) DEFAULT NULL,
	vehicle_version varchar(128) DEFAULT NULL,
	fk_energy integer DEFAULT NULL,
	first_registration_date date DEFAULT NULL,
	commissioning_date date DEFAULT NULL,
	ownership_type varchar(32) DEFAULT NULL,
	fk_soc_owner integer DEFAULT NULL,
	fk_resource integer DEFAULT NULL,
	description text,
	note_public text,
	note_private text,
	status smallint DEFAULT 0 NOT NULL,
	date_creation datetime NOT NULL,
	tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	fk_user_creat integer NOT NULL,
	fk_user_modif integer DEFAULT NULL,
	import_key varchar(14) DEFAULT NULL,
	model_pdf varchar(255) DEFAULT NULL,
	last_main_doc varchar(255) DEFAULT NULL
) ENGINE=innodb;

