CREATE TABLE llx_lmdbvehiclemanagement_control_requirement (
	rowid integer AUTO_INCREMENT PRIMARY KEY,
	entity integer DEFAULT 1 NOT NULL,
	fk_vehicle integer NOT NULL,
	fk_rule integer NOT NULL,
	requirement_kind varchar(16) DEFAULT 'periodic' NOT NULL,
	fk_source_control integer DEFAULT 0 NOT NULL,
	fk_last_control integer DEFAULT NULL,
	qualification_status varchar(16) DEFAULT 'incomplete' NOT NULL,
	applicability_date date DEFAULT NULL,
	calculated_due_date date DEFAULT NULL,
	retained_due_date date DEFAULT NULL,
	status varchar(32) DEFAULT 'incomplete' NOT NULL,
	blocking_mode varchar(16) DEFAULT 'none' NOT NULL,
	fk_actioncomm integer DEFAULT NULL,
	derogation_until datetime DEFAULT NULL,
	derogation_reason text,
	fk_user_derogation integer DEFAULT NULL,
	date_derogation datetime DEFAULT NULL,
	active smallint DEFAULT 1 NOT NULL,
	last_evaluated datetime DEFAULT NULL,
	date_creation datetime NOT NULL,
	tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	fk_user_creat integer NOT NULL,
	fk_user_modif integer DEFAULT NULL
) ENGINE=innodb;
