CREATE TABLE llx_lmdbvehiclemanagement_vehicle_event (
	rowid integer AUTO_INCREMENT PRIMARY KEY,
	entity integer DEFAULT 1 NOT NULL,
	ref varchar(128) NOT NULL,
	fk_vehicle integer NOT NULL,
	event_type varchar(32) NOT NULL,
	event_subtype varchar(64) DEFAULT NULL,
	event_date datetime NOT NULL,
	fk_user_driver integer DEFAULT NULL,
	fk_soc integer DEFAULT NULL,
	label varchar(255) NOT NULL,
	description text,
	severity smallint DEFAULT 1 NOT NULL,
	is_immobilized smallint DEFAULT 0 NOT NULL,
	immobilization_start datetime DEFAULT NULL,
	immobilization_end datetime DEFAULT NULL,
	odometer_km double(24,8) DEFAULT NULL,
	status smallint DEFAULT 0 NOT NULL,
	note_public text,
	note_private text,
	date_creation datetime NOT NULL,
	tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	fk_user_creat integer NOT NULL,
	fk_user_modif integer DEFAULT NULL,
	import_key varchar(14) DEFAULT NULL,
	model_pdf varchar(255) DEFAULT NULL,
	last_main_doc varchar(255) DEFAULT NULL
) ENGINE=innodb;

