CREATE TABLE llx_lmdbvehiclemanagement_consumption (
	rowid integer AUTO_INCREMENT PRIMARY KEY,
	entity integer DEFAULT 1 NOT NULL,
	ref varchar(128) NOT NULL,
	fk_vehicle integer NOT NULL,
	fk_consumable integer NOT NULL,
	category_snapshot varchar(16) NOT NULL,
	unit_snapshot varchar(16) NOT NULL,
	fk_odometer_reading integer NOT NULL,
	fk_user_driver integer DEFAULT NULL,
	quantity double(24,8) NOT NULL,
	total_ttc double(24,8) DEFAULT 0 NOT NULL,
	currency_snapshot varchar(3) NOT NULL,
	oil_reference varchar(128) DEFAULT NULL,
	description text,
	note_public text,
	note_private text,
	status smallint DEFAULT 1 NOT NULL,
	date_creation datetime NOT NULL,
	tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	fk_user_creat integer NOT NULL,
	fk_user_modif integer DEFAULT NULL,
	import_key varchar(14) DEFAULT NULL,
	model_pdf varchar(255) DEFAULT NULL,
	last_main_doc varchar(255) DEFAULT NULL
) ENGINE=innodb;
