CREATE TABLE llx_lmdbvehiclemanagement_insurance_contract (
	rowid integer AUTO_INCREMENT PRIMARY KEY,
	entity integer DEFAULT 1 NOT NULL,
	ref varchar(128) NOT NULL,
	fk_soc integer NOT NULL,
	fk_contact integer DEFAULT NULL,
	policy_number varchar(128) NOT NULL,
	label varchar(255) NOT NULL,
	coverage_formula varchar(255) DEFAULT NULL,
	date_start date NOT NULL,
	date_end date DEFAULT NULL,
	renewal_mode varchar(32) DEFAULT 'fixed' NOT NULL,
	notice_date date DEFAULT NULL,
	assistance_phone varchar(32) DEFAULT NULL,
	assistance_email varchar(255) DEFAULT NULL,
	claim_phone varchar(32) DEFAULT NULL,
	claim_email varchar(255) DEFAULT NULL,
	description text,
	note_public text,
	note_private text,
	status smallint DEFAULT 0 NOT NULL,
	date_creation datetime NOT NULL,
	tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	fk_user_creat integer NOT NULL,
	fk_user_modif integer DEFAULT NULL,
	import_key varchar(14) DEFAULT NULL,
	last_main_doc varchar(255) DEFAULT NULL
) ENGINE=innodb;
