CREATE TABLE llx_lmdbvehiclemanagement_regulatory_rule (
	rowid integer AUTO_INCREMENT PRIMARY KEY,
	entity integer DEFAULT 1 NOT NULL,
	code varchar(64) NOT NULL,
	label varchar(255) NOT NULL,
	description text,
	fk_control_type integer NOT NULL,
	jurisdiction varchar(8) DEFAULT 'FR' NOT NULL,
	territory varchar(32) DEFAULT 'FR_ALL' NOT NULL,
	calculator_code varchar(64) NOT NULL,
	initial_delay_months integer DEFAULT NULL,
	recurrence_months integer DEFAULT NULL,
	recurrence_days integer DEFAULT NULL,
	recheck_days integer DEFAULT NULL,
	effective_from date DEFAULT NULL,
	effective_to date DEFAULT NULL,
	default_blocking_mode varchar(16) DEFAULT 'none' NOT NULL,
	source_title varchar(255) DEFAULT NULL,
	source_url varchar(512) DEFAULT NULL,
	source_review_date date DEFAULT NULL,
	is_native smallint DEFAULT 0 NOT NULL,
	fk_parent_rule integer DEFAULT NULL,
	override_reason text,
	active smallint DEFAULT 1 NOT NULL,
	date_creation datetime NOT NULL,
	tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	fk_user_creat integer DEFAULT NULL,
	fk_user_modif integer DEFAULT NULL
) ENGINE=innodb;
