CREATE TABLE llx_lmdbvehiclemanagement_regulatory_control (
	rowid integer AUTO_INCREMENT PRIMARY KEY,
	entity integer DEFAULT 1 NOT NULL,
	ref varchar(128) NOT NULL,
	fk_vehicle integer NOT NULL,
	fk_requirement integer NOT NULL,
	fk_rule integer NOT NULL,
	control_kind varchar(32) DEFAULT 'periodic' NOT NULL,
	control_date datetime NOT NULL,
	fk_soc_provider integer DEFAULT NULL,
	document_ref varchar(128) DEFAULT NULL,
	result_code varchar(64) DEFAULT NULL,
	official_valid_until date DEFAULT NULL,
	calculated_valid_until date DEFAULT NULL,
	retained_valid_until date DEFAULT NULL,
	due_override_reason text,
	fk_previous_control integer DEFAULT NULL,
	cancellation_reason text,
	observations text,
	note_public text,
	note_private text,
	status smallint DEFAULT 0 NOT NULL,
	date_validation datetime DEFAULT NULL,
	fk_user_valid integer DEFAULT NULL,
	date_cancellation datetime DEFAULT NULL,
	fk_user_cancel integer DEFAULT NULL,
	date_creation datetime NOT NULL,
	tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	fk_user_creat integer NOT NULL,
	fk_user_modif integer DEFAULT NULL,
	import_key varchar(14) DEFAULT NULL,
	model_pdf varchar(255) DEFAULT NULL,
	last_main_doc varchar(255) DEFAULT NULL
) ENGINE=innodb;
